### ISSUE TITLE
error when trying to add a yaml property

### ISSUE THREAD

**Issue by zeltak** [liufree/obsidian-querydash#7]
This looks amazing!

i get an error when i try to add a yaml property ("rating"). here is the error

![Image](https://github.com/user-attachments/assets/9ee7045d-bf37-4869-8733-578397b50100)

here is an example header i have across many file

```
---
tags: 
- 
status: 
rating: 
location: 
counter: 
created:
url:
---
```

and here is the query that gives the error

```
```querydash
table file.name , file.outlinks as "links" ,file.mtime as "mtime",
file.mtime as "mtime", status, rating ,file.tags as "tags" from #chicken/bst
```
```

any clue?

thx!

z

**Comment by liufree** [comment]
@zeltak I have fixed this bug in version 1.0.1. Please update.

#8

**Comment by fornewfork** [comment]
If we **sort** a column with some empty propertie values in it,  it still get an error as follow. Please check it. Thanks!

![Image](https://github.com/user-attachments/assets/67f098eb-9712-4717-b65b-ec8dab57096f)

![Image](https://github.com/user-attachments/assets/18c8fbdd-e88e-43e1-81bf-546f1fc4f7df)

**Comment by liufree** [comment]
@zeltak，thank you， I have fixed this bug in version 1.0.5.
